version: '3'
services:
  mongo:
    build:
      context: ./
      dockerfile: Dockerfile.mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - job_quest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 400M
      restart_policy:
        condition: on-failure

  api:
    build:
      context: ./
      dockerfile: Dockerfile.express
    depends_on:
      - mongo
    networks:
      - job_quest
    ports:
      - 80:80
    restart: always
    volumes:
      - './src:/usr/src/app/src'
      - './index.js:/usr/src/app/index.js'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure

networks:
  job_quest:
    driver: bridge
